name: Update README with latest blog post

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecutar todos los días a medianoche
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install requests
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Get latest blog post
        run: python get_latest_blog_post.py > latest_post.md

      - name: Update README
        run: |
          latest_post=$(cat latest_post.md)
          echo "Updating README.md with latest blog post:"
          echo "${latest_post}"
          sed -i '/<!-- BLOG-POST-START -->/,/<!-- BLOG-POST-END -->/c\<!-- BLOG-POST-START -->\n'"${latest_post}"'\n<!-- BLOG-POST-END -->' README.md
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update README with latest blog post' || echo "No changes to commit"
          git push || echo "No changes to push"